"""empty message

Revision ID: 5e5e0d0bb09f
Revises: 088702e25241
Create Date: 2022-09-14 11:48:04.251826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5e0d0bb09f'
down_revision = '088702e25241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_members', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_members', 'profile_picture')
    # ### end Alembic commands ###
