"""empty message

Revision ID: 7468a3fe2080
Revises: b83a0a8b9c0d
Create Date: 2022-09-12 16:27:40.484607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7468a3fe2080'
down_revision = 'b83a0a8b9c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['club_members.id'], name=op.f('fk_uploads_profile_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    op.create_index(op.f('created_at'), 'uploads', ['created_at'], unique=False)
    op.add_column('event', sa.Column('event_created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('event', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.create_index(op.f('event_created_at'), 'event', ['event_created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('event_created_at'), table_name='event')
    op.drop_column('event', 'updated_at')
    op.drop_column('event', 'event_created_at')
    op.drop_index(op.f('created_at'), table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
