"""empty message

Revision ID: 91870711ec7a
Revises: 7468a3fe2080
Create Date: 2022-09-12 17:18:19.676695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91870711ec7a'
down_revision = '7468a3fe2080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('uploads', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('uploads', sa.Column('mimetype', sa.String(length=255), nullable=False))
    op.add_column('uploads', sa.Column('original', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'original')
    op.drop_column('uploads', 'mimetype')
    op.drop_column('uploads', 'height')
    op.drop_column('uploads', 'width')
    # ### end Alembic commands ###
