"""empty message

Revision ID: b99797eab662
Revises: 4b3938137384
Create Date: 2022-09-29 11:44:17.376219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99797eab662'
down_revision = '4b3938137384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_members', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_index('club_memb_is_active', table_name='club_members')
    op.create_index(op.f('active'), 'club_members', ['active'], unique=False)
    op.drop_column('club_members', 'club_memb_is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_members', sa.Column('club_memb_is_active', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('active'), table_name='club_members')
    op.create_index('club_memb_is_active', 'club_members', ['club_memb_is_active'], unique=False)
    op.drop_column('club_members', 'active')
    # ### end Alembic commands ###
