import os

DEBUG = True
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
FLASK_ENV='development'
# SECRET_KEY = 'thisissecretkey'
# DATABASEUSERNAME='stonex'
# DATABASEPASSWORD='ArcInd#123'
DATABASEHOST='127.0.0.1'
SECRETKEY='Sm9obiBTY2hyb20ga2lja3MgYXNz'
ENV='PROD11'
FLASK_APP = 'run'